Controllers/GadgetsController.cs
using JamesBondGadgetsEntity.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JamesBondGadgetsEntity.Controllers
{
    public class GadgetsController : Controller
    {
        private ApplicationDbContext context;

        public GadgetsController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        // GET: Gadgets
        public ActionResult Index()
        {


            return View("Index");
        }

        public ActionResult Details(int id)
        {


            return View("Details");
        }

        public ActionResult Create()
        {
            return View("GadgetForm");
        }

        public ActionResult Edit(int id)
        {

            return View("GadgetForm");
        }

        public ActionResult Delete(int id)
        {

            return View("Index");
        }

        public ActionResult ProcessCreate(GadgetModel gadgetModel)
        {
            // save to the db



            return View("Details", gadgetModel);
        }

        public ActionResult SearchForm()
        {
            return View("SearchForm");
        }

        public ActionResult SearchForName(string searchPhrase)
        {
            // get a list of search results from the database



            return View("Index");
        }

        public ActionResult SearchForDescription(string searchPhrase)
        {
            // get a list of search results from the database


            return View("Index");
        }
    }
}

Views/Gadgets/Details.cshtml
@model JamesBondGadgetsEntity.Models.GadgetModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>GadgetModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppearsIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppearsIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WithThisActor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WithThisActor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Gadgets/GadgetForm.cshtml
@model JamesBondGadgetsEntity.Models.GadgetModel

@{
    ViewBag.Title = "GadgetForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GadgetForm</h2>


@using (Html.BeginForm("ProcessCreate", "Gadgets")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GadgetModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AppearsIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AppearsIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AppearsIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WithThisActor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WithThisActor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WithThisActor, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" name="Id" value="@Model.Id" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Gadgets/Index.cshtml
@model IEnumerable<JamesBondGadgetsEntity.Models.GadgetModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppearsIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WithThisActor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppearsIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WithThisActor)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Gadgets/SearchForm.cshtml
@model JamesBondGadgetsEntity.Models.GadgetModel

@{
    ViewBag.Title = "SearchForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Form</h2>


@using (Html.BeginForm("SearchForName", "Gadgets"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GadgetModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                <label for="searchPhrase">Search by Name</label>
                <input type="text" name="searchPhrase" id="searchPhrase" class="form-control" />

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<p>Search Description</p>

@using (Html.BeginForm("SearchForDescription", "Gadgets"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GadgetModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                <label for="searchPhrase">Search by Description</label>
                <input type="text" name="searchPhrase" id="searchPhrase" class="form-control" />

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}